export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const GET_CITY_HOTELS = 'GET_CITY_HOTELS';
export const SET_CITY_INFO = 'SET_CITY_INFO';
export const COLLECT_FAVORITE = 'COLLECT_FAVORITE';
export const ERASE_FAVORITES = 'ERASE_FAVORITES';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const SORT_FAVORITES = 'SORT_FAVORITES';